### ISSUE TITLE
Error when converting a form that uses "id_string" rather than "form_id"

### ISSUE THREAD

**Issue by joeflack4** [PMA-2020/ppp#31]
## Description
When trying to convert a form where the form id in the "settings" worksheet is set on a field called "id_string" instead of "form_id", this produces an error.

This is likely to be common for forms created for the popular survey platform "SurveyCTO".

### Expected behavior 
Converting does not produce an error.

### Actual behavior 
A `TypeError: 'NoneType' object is not subscriptable` is received.
```
Traceback (most recent call last):
File "/app/.heroku/python/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/app/.heroku/python/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/app/.heroku/python/lib/python3.6/site-packages/ppp/__main__.py", line 8, in <module>
cli()
File "/app/.heroku/python/lib/python3.6/site-packages/ppp/interfaces/cli.py", line 228, in cli
debug=args.debug, highlight=args.highlight, preset=args.preset)
File "/app/.heroku/python/lib/python3.6/site-packages/ppp/__init__.py", line 159, in run
convert_file(file, language, outpath=_outpath, **combo)
File "/app/.heroku/python/lib/python3.6/site-packages/ppp/__init__.py", line 49, in convert_file
form = OdkForm.from_file(in_file)
File "/app/.heroku/python/lib/python3.6/site-packages/ppp/odkform.py", line 89, in from_file
return cls(xlsform)
File "/app/.heroku/python/lib/python3.6/site-packages/ppp/odkform.py", line 62, in __init__
'country': self.settings.get('form_id')[3:5],
TypeError: 'NoneType' object is not subscriptable
```

### Additional details
The reason the type is `None` is because PPP is looking for a field called "form_id". When it doesn't find any, it returns the type `None`.

### 1. Fix the error
Fix the error as described in this issue.

Possible solutions:
- Have PPP look for either "id_string" or "form_id", rather than just for "form_id".

### 2. Add a test case
The test should be added to `test/test_ppp.py`.

It should be a class inheriting from the `PppTest` class. Something like this should work,

```
class IdStringSupport(PppTest):
    """Successfully creates a form when the form ID is called "id_string" rather than "form_id"."""

    def test_convert(self):
        self.standard_conversion_test()
```

After this, you should be able to make a folder in `test/files/` called `IdStringSupport`. Inside that folder, put another folder called `input`. Then, place the test .xlsx file in there.

## Task list
- [ ] 1. Fix the error
- [ ] 2. Add a test case

**Comment by joeflack4** [comment]
Merged.
