### ISSUE TITLE
IndexError: list out of range

### ISSUE THREAD

**Issue by joeflack4** [PMA-2020/ppp#39]
## Description
When converting the attached form, the following error is produced:
> `IndexError: list out of range`

---

**Attachments**
1. [index error - list out of range.zip](https://github.com/PMA-2020/ppp/files/2416560/index.error.-.list.out.of.range.zip)

**Comment by joeflack4** [comment]
another case:
```
Joe:Desktop joeflack4$ python3 -m ppp *.xlsx --format html doc --template old --language English Swahili --preset standard --outpath ./out/
Creating files.
./out/KEP1-Female-Questionnaire-v1-jef-English.html
./out/KEP1-Female-Questionnaire-v1-jef-English.doc
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ppp/__main__.py", line 8, in <module>
    cli()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ppp/interfaces/cli.py", line 239, in cli
    outpath=args.outpath)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ppp/__init__.py", line 158, in run
    convert_file(file, language, outpath=_outpath, **combo)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ppp/__init__.py", line 62, in convert_file
    output = form.to_html(lang=language, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ppp/odkform.py", line 369, in to_html
    html_questionnaire += item.to_html(lang=language, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ppp/odkgroup.py", line 139, in to_html
    html += i.to_html(lang, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ppp/odktable.py", line 138, in to_html
    self.set_header_and_contents(lang, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ppp/odktable.py", line 77, in set_header_and_contents
    con.row['label'] = con.row['label'][0]
IndexError: string index out of range
```

[KEP1-Female-Questionnaire-v1-jef.xlsx](https://github.com/PMA-2020/ppp/files/3658991/KEP1-Female-Questionnaire-v1-jef.xlsx)
